### ISSUE TITLE
Problems getting Json_data

### ISSUE THREAD

**Issue by tommydino** [iganeshk/LaMetric-System-Monitor#3]
The script now it is searching for sensores HWinfo is running
and i start the remotehwinfo.exe with the Arguments: -port 8085 -hwinfo 1 -gpuz 0 -afterburner 0 -log 0
And the script crashes

Traceback (most recent call last):
File "C:\Users\xxxxx\LaMetric-System-Monitor\lametricSysMon.py", line 176, in
parse_ohm()
File "C:\Users\xxxx\LaMetric-System-Monitor\lametricSysMon.py", line 108, in parse_ohm
cpu_temp = json_data['hwinfo']['readings'][
~~~~~~~~~^^^^^^^^^^
KeyError: 'hwinfo'

Im using HWinfo version 7.62

**Comment by tommydino** [comment]
The error over is now fixed.
But try the script now it is searching for sensores HWinfo is running
and i start the remotehwinfo.exe with the Arguments: -port 8085 -hwinfo 1 -gpuz 0 -afterburner 0 -log 0
And the script crashes

Traceback (most recent call last):
  File "C:\Users\*****\LaMetric-System-Monitor\lametricSysMon.py", line 176, in <module>
    parse_ohm()
  File "C:\Users\*****\LaMetric-System-Monitor\lametricSysMon.py", line 108, in parse_ohm
    cpu_temp = json_data['hwinfo']['readings'][
               ~~~~~~~~~^^^^^^^^^^
KeyError: 'hwinfo'
